## Series

### Creating Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.array([1,2,3])
labels  = ['a','b','c']
Dis = {'a' : 10, 'b' : 20, 'c' : 30}
my_list = [2,4,6]
my_list

[2, 4, 6]

In [3]:
pd.Series(my_list,labels)

a    2
b    4
c    6
dtype: int64

# Data Fream

In [4]:
Data =  {'Name':["Farhan","Sayeed","Zunayeed","Kamrul"],
         'City':["Dhaka","Sharpur","Kusthiya","Bhola"],
         "Age":[25,26,28,25],
         'Salary':[50000,55000,80000,4000]
        }
Label = ['a','b','c','d']
df = pd.DataFrame(Data,Label)
df

       Name      City  Age  Salary
a    Farhan     Dhaka   25   50000
b    Sayeed   Sharpur   26   55000
c  Zunayeed  Kusthiya   28   80000
d    Kamrul     Bhola   25    4000

In [5]:
DataList = [["Farhan",10,1000],
            ["Kamrul" , 20 ,2000],
            ["Sayeed",30,30000], 
           ['Sikder',20,40000]
           ]
columnnnn = ["Name","Age","Salary"]
df1 = pd.DataFrame(DataList,Label,columns = columnnnn)
df1

     Name  Age  Salary
a  Farhan   10    1000
b  Kamrul   20    2000
c  Sayeed   30   30000
d  Sikder   20   40000

In [6]:
df1["Name"]

a    Farhan
b    Kamrul
c    Sayeed
d    Sikder
Name: Name, dtype: object

In [7]:
df1[["Name","Age"]]

     Name  Age
a  Farhan   10
b  Kamrul   20
c  Sayeed   30
d  Sikder   20

In [8]:
df1['City']=["Dhaka","Cumillah","Rongpur","Dinajpur"]
df1

     Name  Age  Salary      City
a  Farhan   10    1000     Dhaka
b  Kamrul   20    2000  Cumillah
c  Sayeed   30   30000   Rongpur
d  Sikder   20   40000  Dinajpur

In [9]:
df1.drop('City',axis = 1)

     Name  Age  Salary
a  Farhan   10    1000
b  Kamrul   20    2000
c  Sayeed   30   30000
d  Sikder   20   40000

In [10]:
df1

     Name  Age  Salary      City
a  Farhan   10    1000     Dhaka
b  Kamrul   20    2000  Cumillah
c  Sayeed   30   30000   Rongpur
d  Sikder   20   40000  Dinajpur

In [11]:
df1.drop('City',axis = 1, inplace = True)
df1

     Name  Age  Salary
a  Farhan   10    1000
b  Kamrul   20    2000
c  Sayeed   30   30000
d  Sikder   20   40000

In [12]:
df1.iloc[[0,3]]

     Name  Age  Salary
a  Farhan   10    1000
d  Sikder   20   40000

In [13]:
df1.loc[['a','b'],['Salary','Age']]

   Salary  Age
a    1000   10
b    2000   20

In [14]:
df1

     Name  Age  Salary
a  Farhan   10    1000
b  Kamrul   20    2000
c  Sayeed   30   30000
d  Sikder   20   40000

In [15]:
df1.loc[['c','d'],['Salary','Name']]

   Salary    Name
c   30000  Sayeed
d   40000  Sikder

## Conditional Selection

In [16]:
df1[df1['Age']>= 20]

     Name  Age  Salary
b  Kamrul   20    2000
c  Sayeed   30   30000
d  Sikder   20   40000

In [17]:
df1[(df1['Age']>=20) & (df1['Salary']>= 25000)]

     Name  Age  Salary
c  Sayeed   30   30000
d  Sikder   20   40000

# Mising Data

In [18]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df3 = pd.DataFrame(data)
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.isna()

    Name   City    Age  Salary
a  False  False  False   False
b  False  False  False   False
c  False  False  False   False
d  False  False  False   False

In [20]:
df.isna().count()

Name      4
City      4
Age       4
Salary    4
dtype: int64

In [22]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [23]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [25]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [26]:
pd.merge(employees,salaries,on='employee_id')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

# Concate

In [29]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [31]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [32]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# Joining

In [36]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [37]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

# Groupby and Aggregation

In [39]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [40]:
df['Sales'].agg(['sum','mean','min','max','count','std','median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

# Pivot Table

In [41]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    282     91   John  January      Q1
1  2023-01-02       B   West    427     23   Mary  January      Q1
2  2023-01-03       C  North    402     30    Bob  January      Q1
3  2023-01-04       D  South    640     80  Alice  January      Q1
4  2023-01-05       A   East    140     99   John  January      Q1
5  2023-01-06       B   West    292     40   Mary  January      Q1
6  2023-01-07       C  North    530     43    Bob  January      Q1
7  2023-01-08       D  South    462     93  Alice  January      Q1
8  2023-01-09       A   East    970     61   John  January      Q1
9  2023-01-10       B   West    569     50   Mary  January      Q1
10 2023-01-11       C  North    320     35    Bob  January      Q1
11 2023-01-12       D  South    757     32  Alice  January      Q1
12 2023-01-13       A   East    888     99   John  January      Q1
13 2023-01-14       B   West    742     42   Mary  January      Q1
14 2023-01-15       C  North    720     50    Bob  January      Q1
15 2023-01-16       D  South    875     84  Alice  January      Q1
16 2023-01-17       A   East    622     55   John  January      Q1
17 2023-01-18       B   West    747     59   Mary  January      Q1
18 2023-01-19       C  North    367     54    Bob  January      Q1
19 2023-01-20       D  South    854     23  Alice  January      Q1

pd.pivot_table(df,values = 'Sales' , index = 'Region', columns = 'Product')

In [49]:
pd.pivot_table(df, values = ['Sales', 'Units'],index = 'Region', columns = 'Product',aggfunc=("mean",'max'))

         Sales                                                  Units        \
           max                        mean                        max
Product      A      B      C      D      A      B      C      D     A     B
Region
East     970.0    NaN    NaN    NaN  580.4    NaN    NaN    NaN  99.0   NaN
North      NaN    NaN  720.0    NaN    NaN    NaN  467.8    NaN   NaN   NaN
South      NaN    NaN    NaN  875.0    NaN    NaN    NaN  717.6   NaN   NaN
West       NaN  747.0    NaN    NaN    NaN  555.4    NaN    NaN   NaN  59.0


                     mean
Product     C     D     A     B     C     D
Region
East      NaN   NaN  81.0   NaN   NaN   NaN
North    54.0   NaN   NaN   NaN  42.4   NaN
South     NaN  93.0   NaN   NaN   NaN  62.4
West      NaN   NaN   NaN  42.8   NaN   NaN

In [50]:
# Cross Tab

In [53]:
pd.crosstab(df['Product'],df['Sales'])

Sales,140,282,292,320,367,402,427,462,530,569,622,640,720,742,747,757,854,875,888,970
Product,,,,,,,,,,,,,,,,,,,,
A,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1
B,0,0,1,0,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,0
C,0,0,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0
D,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,1,0,0